// Autogenerated file
const translationKeys = {
  common: {
    club_name: 'common.club_name',
  },
  navbar: {
    home_link: 'navbar.home_link',
  },
};

Object.freeze(translationKeys);

export default translationKeys;
