// Autogenerated file
const translationKeys = {
  common: {
    club_name: 'common.club_name',
  },
  navbar: {
    home: 'navbar.home',
    news: 'navbar.news',
    about_us: 'navbar.about_us',
    training: 'navbar.training',
    schedule: 'navbar.schedule',
  },
};

Object.freeze(translationKeys);

export default translationKeys;
